### ISSUE TITLE
상태코드(sts)가 4에 관해

### ISSUE THREAD

**Issue by saroro1** [k0deh0lic/metroLib#7]
원천 데이터 상태코드(sts)는 다음과 같습니다
1.  진입
1.  도착
1.  출발
1.  이동(출발)

하지만 현재 라인 전체 불러오는 원천 데이터는 상태코드가 4인경우 stationNm가 현재역이 아닌 다음역으로  나옵니다
sts가 4일 때 출발로 처리하지 마시고 혹시 진입으로 처리가 가능하신가요?  

현재 역으로 조회하였을 시 일부 내용입니다
```yaml
{
            "trainY": "S4096",
            "trainP": "0403",
            "trainC": null,
            "sts": 4,
            "stsNm": null,
            "dir": 1,
            "dirNm": null,
            "orgStn": 24,
            "orgStnCd": null,
            "orgStnNm": null,
            "dstStn": 91,
            "dstStnCd": "0409",
            "dstStnNm": "당고개",
            "line": "4",
            "complainCnt": 0,
            "frontGbn": 0,
            "arvTime": null,
            "startStnCd": "0423",
            "startStnNm": "충무로",
            "endStnCd": "0422",
            "endStnNm": "동대문역사문화공원",
            "stationCd": null,
            "stationNm": null
}
```
startStnNm이 **충무로**이므로 충무로 출발이 맞으나 전체를 불러왔을 경우 stationNm이 **동대문역사문화공원**으로 나와   
'**동대문역사문화공원**' 출발로 나옵니다. 이런 경우 **동대문역사문화공원**'진입으로 처리 해주셨으면 좋겠습니다
